name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Senzo13
          BRANCH_NAME: github-profile-summary-cards
          UTC_OFFSET: 1
          AUTO_PUSH: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Push to branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: github-profile-summary-cards
          build_dir: profile-summary-card-output
          keep_history: true
          commit_message: "Update profile summary cards"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
